-- CarePilot v0.1: Supabase / PostgreSQL schema for the current local prototype.
--
-- Scope: the 12 persistent entities implemented in apps/api/app/models.py.
-- This is intentionally not an Evidence Storage, Redis, RAG, or authentication
-- migration: those components are not implemented by the current prototype.
--
-- Apply once to an empty CarePilot Supabase project using the SQL Editor.
-- It creates no demo data and contains no DROP TABLE, TRUNCATE, or client-access policy.
-- The ticket trigger is replaced idempotently so the script can be re-applied.

begin;

create table if not exists public.tickets (
    id varchar(32) primary key,
    title varchar(240) not null,
    customer varchar(120) not null,
    category varchar(60) not null,
    scenario varchar(60) not null,
    risk varchar(16) not null check (risk in ('LOW', 'MEDIUM', 'HIGH')),
    status varchar(32) not null check (status in ('NEW', 'PROCESSING', 'NEED_INFO', 'WAITING_REVIEW', 'RESOLVED', 'FAILED')),
    evidence_submitted boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.action_proposals (
    id integer generated by default as identity primary key,
    ticket_id varchar(32) not null references public.tickets(id),
    action varchar(80) not null,
    status varchar(32) not null default 'PENDING' check (status in ('PENDING', 'AUTO_EXECUTED', 'APPROVED', 'MODIFIED', 'REJECTED', 'TAKEN_OVER')),
    rationale text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.tool_executions (
    id integer generated by default as identity primary key,
    ticket_id varchar(32) not null references public.tickets(id),
    tool_name varchar(80) not null,
    outcome varchar(24) not null,
    summary text not null,
    idempotency_key varchar(120) unique,
    created_at timestamptz not null default now()
);

create table if not exists public.human_reviews (
    id integer generated by default as identity primary key,
    ticket_id varchar(32) not null references public.tickets(id),
    decision varchar(32) not null check (decision in ('APPROVE', 'MODIFY', 'REJECT', 'TAKE_OVER')),
    note text,
    reviewer varchar(120) not null default 'demo-operator',
    created_at timestamptz not null default now()
);

create table if not exists public.audit_events (
    id integer generated by default as identity primary key,
    ticket_id varchar(32) not null references public.tickets(id),
    event_type varchar(80) not null,
    summary text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.policy_sources (
    id varchar(48) primary key,
    title varchar(240) not null,
    source_type varchar(32) not null,
    sync_schedule varchar(80) not null,
    last_synced_at timestamptz
);

create table if not exists public.policy_versions (
    id integer generated by default as identity primary key,
    source_id varchar(48) not null references public.policy_sources(id),
    version varchar(32) not null,
    status varchar(32) not null check (status in ('CANDIDATE', 'ACTIVE', 'ARCHIVED')),
    diff_summary text not null,
    created_at timestamptz not null default now(),
    published_by varchar(120)
);

create table if not exists public.policy_regression_runs (
    id integer generated by default as identity primary key,
    policy_version_id integer not null references public.policy_versions(id),
    status varchar(32) not null check (status in ('PENDING', 'PASSED', 'FAILED')),
    summary text not null,
    completed_at timestamptz
);

create table if not exists public.policy_audit_events (
    id integer generated by default as identity primary key,
    source_id varchar(48) not null references public.policy_sources(id),
    policy_version_id integer references public.policy_versions(id),
    event_type varchar(80) not null,
    summary text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.agent_config_versions (
    id integer generated by default as identity primary key,
    version varchar(32) not null,
    status varchar(32) not null check (status in ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    model_name varchar(120) not null,
    prompt_version varchar(80) not null,
    tool_allowlist text not null,
    risk_boundary text not null,
    activated_by varchar(120),
    created_at timestamptz not null default now()
);

create table if not exists public.config_sandbox_runs (
    id integer generated by default as identity primary key,
    config_version_id integer not null references public.agent_config_versions(id),
    scenario_id varchar(80) not null,
    status varchar(32) not null check (status in ('PENDING', 'PASSED')),
    summary text not null,
    completed_at timestamptz
);

create table if not exists public.config_audit_events (
    id integer generated by default as identity primary key,
    config_version_id integer not null references public.agent_config_versions(id),
    event_type varchar(80) not null,
    summary text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.evaluation_runs (
    id integer generated by default as identity primary key,
    fixture_set varchar(120) not null,
    execution_mode varchar(40) not null,
    sample_size integer not null check (sample_size > 0),
    status varchar(32) not null,
    manual_avg_minutes double precision not null check (manual_avg_minutes >= 0),
    agent_avg_minutes double precision not null check (agent_avg_minutes >= 0),
    proposal_modification_rate double precision not null check (proposal_modification_rate between 0 and 100),
    policy_top3_hit_rate double precision not null check (policy_top3_hit_rate between 0 and 100),
    tool_failure_rate double precision not null check (tool_failure_rate between 0 and 100),
    p95_latency_seconds double precision not null check (p95_latency_seconds >= 0),
    avg_cost_usd double precision not null check (avg_cost_usd >= 0),
    bad_cases_json text not null,
    source_note text not null,
    completed_at timestamptz not null default now()
);

-- A prior local prototype created evaluation_runs before the frozen-evaluation
-- fields existed. CREATE TABLE IF NOT EXISTS preserves that table, so make the
-- base schema safe to re-run before creating the fixture_set index below.
alter table public.evaluation_runs add column if not exists fixture_set varchar(120) not null default 'legacy-unknown';
alter table public.evaluation_runs add column if not exists execution_mode varchar(40) not null default 'SIMULATED_OFFLINE';
alter table public.evaluation_runs add column if not exists sample_size integer not null default 1;
alter table public.evaluation_runs add column if not exists status varchar(32) not null default 'PASSED';
alter table public.evaluation_runs add column if not exists manual_avg_minutes double precision not null default 0;
alter table public.evaluation_runs add column if not exists agent_avg_minutes double precision not null default 0;
alter table public.evaluation_runs add column if not exists proposal_modification_rate double precision not null default 0;
alter table public.evaluation_runs add column if not exists policy_top3_hit_rate double precision not null default 0;
alter table public.evaluation_runs add column if not exists tool_failure_rate double precision not null default 0;
alter table public.evaluation_runs add column if not exists p95_latency_seconds double precision not null default 0;
alter table public.evaluation_runs add column if not exists avg_cost_usd double precision not null default 0;
alter table public.evaluation_runs add column if not exists bad_cases_json text not null default '[]';
alter table public.evaluation_runs add column if not exists source_note text not null default 'Legacy evaluation record; not real model evidence.';
alter table public.evaluation_runs add column if not exists completed_at timestamptz not null default now();

create index if not exists tickets_status_idx on public.tickets (status);
create index if not exists action_proposals_ticket_id_idx on public.action_proposals (ticket_id);
create index if not exists tool_executions_ticket_id_idx on public.tool_executions (ticket_id);
create index if not exists human_reviews_ticket_id_idx on public.human_reviews (ticket_id);
create index if not exists audit_events_ticket_id_idx on public.audit_events (ticket_id);
create index if not exists policy_versions_source_id_idx on public.policy_versions (source_id);
create index if not exists policy_versions_status_idx on public.policy_versions (status);
create index if not exists policy_regression_runs_version_id_idx on public.policy_regression_runs (policy_version_id);
create index if not exists policy_audit_events_source_id_idx on public.policy_audit_events (source_id);
create index if not exists policy_audit_events_version_id_idx on public.policy_audit_events (policy_version_id);
create index if not exists agent_config_versions_status_idx on public.agent_config_versions (status);
create index if not exists config_sandbox_runs_config_id_idx on public.config_sandbox_runs (config_version_id);
create index if not exists config_audit_events_config_id_idx on public.config_audit_events (config_version_id);
create index if not exists evaluation_runs_fixture_set_idx on public.evaluation_runs (fixture_set);

create or replace function public.carepilot_set_ticket_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists carepilot_tickets_set_updated_at on public.tickets;
create trigger carepilot_tickets_set_updated_at
before update on public.tickets
for each row execute function public.carepilot_set_ticket_updated_at();

-- The browser must not access operational or audit data directly. The current
-- FastAPI server uses a trusted PostgreSQL connection; the Supabase service role
-- is reserved for a future server-only REST integration and is never client-side.
alter table public.tickets enable row level security;
alter table public.action_proposals enable row level security;
alter table public.tool_executions enable row level security;
alter table public.human_reviews enable row level security;
alter table public.audit_events enable row level security;
alter table public.policy_sources enable row level security;
alter table public.policy_versions enable row level security;
alter table public.policy_regression_runs enable row level security;
alter table public.policy_audit_events enable row level security;
alter table public.agent_config_versions enable row level security;
alter table public.config_sandbox_runs enable row level security;
alter table public.config_audit_events enable row level security;
alter table public.evaluation_runs enable row level security;

revoke all privileges on table public.tickets, public.action_proposals, public.tool_executions, public.human_reviews, public.audit_events, public.policy_sources, public.policy_versions, public.policy_regression_runs, public.policy_audit_events, public.agent_config_versions, public.config_sandbox_runs, public.config_audit_events, public.evaluation_runs from anon, authenticated;
grant all privileges on table public.tickets, public.action_proposals, public.tool_executions, public.human_reviews, public.audit_events, public.policy_sources, public.policy_versions, public.policy_regression_runs, public.policy_audit_events, public.agent_config_versions, public.config_sandbox_runs, public.config_audit_events, public.evaluation_runs to service_role;
grant usage, select on sequence public.action_proposals_id_seq, public.tool_executions_id_seq, public.human_reviews_id_seq, public.audit_events_id_seq, public.policy_versions_id_seq, public.policy_regression_runs_id_seq, public.policy_audit_events_id_seq, public.agent_config_versions_id_seq, public.config_sandbox_runs_id_seq, public.config_audit_events_id_seq, public.evaluation_runs_id_seq to service_role;

commit;
