-- CarePilot v0.1: simulated Evidence metadata for the local API prototype.
--
-- Apply only after 001, 002, and 003. This migration does not create a Storage
-- bucket or retain image bytes. The API records only sanitized-file metadata and
-- deterministic simulated-analysis output; original filenames are represented by
-- SHA-256 digests to avoid persisting incidental personal information.

begin;

create table if not exists public.evidence_assets (
    id integer generated by default as identity primary key,
    ticket_id varchar(32) not null references public.tickets(id),
    fixture_id varchar(80),
    source_name_sha256 char(64) not null,
    content_type varchar(24) not null check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
    input_byte_size integer not null check (input_byte_size > 0 and input_byte_size <= 8388608),
    sanitized_byte_size integer not null check (sanitized_byte_size > 0 and sanitized_byte_size <= 8388608),
    content_sha256 char(64) not null,
    exif_removed boolean not null,
    analysis_origin varchar(32) not null check (analysis_origin in ('FIXTURE_ANNOTATION', 'UNASSESSED')),
    evidence_type varchar(48) not null,
    damage_type varchar(80),
    damage_location varchar(120),
    packaging_status varchar(120),
    missing_parts varchar(160),
    label_match varchar(32) not null,
    image_quality varchar(32) not null,
    confidence double precision not null check (confidence between 0 and 1),
    needs_human_review boolean not null,
    review_reason varchar(120),
    created_at timestamptz not null default now()
);

create index if not exists evidence_assets_ticket_id_idx on public.evidence_assets (ticket_id);

alter table public.evidence_assets enable row level security;
revoke all privileges on table public.evidence_assets from anon, authenticated;
grant all privileges on table public.evidence_assets to service_role;
grant usage, select on sequence public.evidence_assets_id_seq to service_role;

commit;
