-- CarePilot v0.1: auditable public-policy grounding for the Policy retrieval layer.
--
-- Apply only after 001, 002, 003, and 004. This migration adds metadata and
-- immutable imported snapshots for a curated, public policy pack. It does not
-- connect to an order, logistics, payment, refund, inventory, or customer-data
-- system, and it creates no browser-readable policy.

begin;

alter table public.policy_sources
    add column if not exists publisher varchar(160),
    add column if not exists source_url text,
    add column if not exists source_scope varchar(48) not null default 'SELF_AUTHORED_SIMULATION',
    add column if not exists source_version_label varchar(200),
    add column if not exists source_published_at timestamptz,
    add column if not exists current_checksum char(64),
    add column if not exists last_verified_at timestamptz;

create table if not exists public.policy_source_snapshots (
    id integer generated by default as identity primary key,
    source_id varchar(48) not null references public.policy_sources(id),
    pack_id varchar(120) not null,
    source_url text not null,
    publisher varchar(160) not null,
    source_version_label varchar(200) not null,
    source_published_at timestamptz,
    retrieved_at timestamptz not null,
    content_checksum char(64) not null,
    source_excerpt text not null,
    import_method varchar(48) not null check (import_method in ('CURATED_PUBLIC_PACK')),
    created_at timestamptz not null default now(),
    unique (source_id, content_checksum)
);

alter table public.policy_versions
    add column if not exists source_snapshot_id integer references public.policy_source_snapshots(id);

create table if not exists public.policy_grounding_chunks (
    id integer generated by default as identity primary key,
    snapshot_id integer not null references public.policy_source_snapshots(id),
    chunk_key varchar(100) not null,
    category varchar(32) not null check (category in ('ALL', 'DIGITAL', 'APPAREL', 'HOME')),
    title varchar(240) not null,
    content text not null,
    keywords_json text not null,
    created_at timestamptz not null default now(),
    unique (snapshot_id, chunk_key)
);

create index if not exists policy_source_snapshots_source_id_idx on public.policy_source_snapshots (source_id, retrieved_at desc);
create index if not exists policy_grounding_chunks_snapshot_id_idx on public.policy_grounding_chunks (snapshot_id);
create index if not exists policy_versions_source_snapshot_id_idx on public.policy_versions (source_snapshot_id);

alter table public.policy_source_snapshots enable row level security;
alter table public.policy_grounding_chunks enable row level security;
revoke all privileges on table public.policy_source_snapshots, public.policy_grounding_chunks from anon, authenticated;
grant all privileges on table public.policy_source_snapshots, public.policy_grounding_chunks to service_role;
grant usage, select on sequence public.policy_source_snapshots_id_seq, public.policy_grounding_chunks_id_seq to service_role;

comment on table public.policy_source_snapshots is 'Immutable, curated public-policy imports. A snapshot never auto-publishes a policy version.';
comment on table public.policy_grounding_chunks is 'Short retrieval chunks grounded in a policy_source_snapshot; orders, logistics, refunds and inventory remain simulated.';

commit;
