-- CarePilot v1: public customer-efficiency study records.
-- Apply after 001 through 010. This migration only adds isolated study tables;
-- it does not alter existing tickets, Agent Runs, policies, users, or v0.2 data.

begin;

create table if not exists public.customer_efficiency_participants (
    id varchar(36) primary key,
    study_mode varchar(16) not null check (study_mode in ('PILOT', 'FORMAL')),
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create table if not exists public.customer_efficiency_assignments (
    id bigint generated by default as identity primary key,
    participant_id varchar(36) not null references public.customer_efficiency_participants(id) on delete cascade,
    task_id varchar(32) not null,
    pair_id varchar(24) not null,
    condition varchar(24) not null check (condition in ('MANUAL', 'DECISION_PACKAGE')),
    round integer not null check (round between 1 and 6),
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    constraint customer_efficiency_assignments_participant_task_unique unique (participant_id, task_id),
    constraint customer_efficiency_assignments_participant_round_unique unique (participant_id, round)
);

create table if not exists public.customer_efficiency_records (
    id bigint generated by default as identity primary key,
    participant_id varchar(36) not null references public.customer_efficiency_participants(id) on delete cascade,
    assignment_id bigint not null unique references public.customer_efficiency_assignments(id) on delete cascade,
    study_mode varchar(16) not null check (study_mode in ('PILOT', 'FORMAL')),
    task_id varchar(32) not null,
    pair_id varchar(24) not null,
    condition varchar(24) not null check (condition in ('MANUAL', 'DECISION_PACKAGE')),
    round integer not null check (round between 1 and 6),
    category varchar(60) not null,
    scenario varchar(80) not null,
    risk varchar(16) not null,
    selected_outcome varchar(32) not null check (selected_outcome in ('RESOLVED', 'NEED_INFO', 'WAITING_REVIEW')),
    outcome_correct boolean not null,
    started_at timestamptz not null,
    completed_at timestamptz not null default now(),
    duration_seconds integer not null check (duration_seconds >= 0),
    source_actions_json text not null default '[]',
    source_fields_viewed_json text not null default '[]',
    decision_package_ready_fields_json text not null default '[]',
    decision_package_missing_fields_json text not null default '[]',
    information_completeness_percent numeric(5,2) not null check (information_completeness_percent between 0 and 100),
    high_risk_gate_observed boolean,
    proposal_outcome varchar(16) check (proposal_outcome is null or proposal_outcome in ('ADOPTED', 'MODIFIED', 'REJECTED', 'TAKEN_OVER')),
    ease_rating_1_to_7 integer not null check (ease_rating_1_to_7 between 1 and 7),
    observer_notes text not null default '',
    constraint customer_efficiency_records_participant_task_unique unique (participant_id, task_id)
);

create index if not exists customer_efficiency_assignments_task_idx on public.customer_efficiency_assignments (task_id);
create index if not exists customer_efficiency_records_mode_task_idx on public.customer_efficiency_records (study_mode, task_id);
create index if not exists customer_efficiency_records_participant_idx on public.customer_efficiency_records (participant_id);

alter table public.customer_efficiency_participants enable row level security;
alter table public.customer_efficiency_assignments enable row level security;
alter table public.customer_efficiency_records enable row level security;

revoke all on table public.customer_efficiency_participants, public.customer_efficiency_assignments, public.customer_efficiency_records from anon, authenticated;
grant all on table public.customer_efficiency_participants, public.customer_efficiency_assignments, public.customer_efficiency_records to service_role;

comment on table public.customer_efficiency_participants is 'Anonymous public-study sessions. The id is a browser-generated UUID, not a Supabase Auth identity.';
comment on table public.customer_efficiency_assignments is 'Server-assigned six-task queue. Assignment state is kept separately from submitted records to prevent duplicate counting.';
comment on table public.customer_efficiency_records is 'Formal and pilot customer-efficiency study records. No names, real orders, uploads, screenshots, model keys, or real actions are stored.';

commit;
